spring:
    jwt:
        secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    application:
        name: theartimposter
    profiles:
        active: secrets
    jpa:
        database-platform: org.hibernate.dialect.OracleDialect
        hibernate:
            ddl-auto: update
            show_sql: true
            use_sql_comments: true
    security:
        oauth2:
            client:
                registration:
                    naver:
                        client-name: naver
                        client-id: dOFDVMYYT33v3ev_vZA2
                        client-secret: vJthwQhtfA
                        redirect-uri: http://localhost:8080/login/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        scope:
                            - name
                            - email
                            - profile_image
                    google:
                        client-name: google
                        client-id: 66645551607-2kdvla28jhcn00aeik11819tupcbru6r.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://localhost:8080/login/oauth2/code/google
                        authorization-grant-type: authorization_code
                        scope:
                            - profile
                            - email
                    kakao:
                        client-name: kakao
                        client-id: ce740ac365ae42744cb64879e9f49f48
                        client-secret: McCZRKYm6V8JkEgWclZUcqL92ICXhSAp
                        client-authentication-method: client_secret_post
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        scope:
                            - profile_nickname
                            - account_email
                provider:
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace


oracle:
    net:
    ssl_server_dn_match: true





