spring:

    application:
        name: theartimposter
    profiles:
        active: secrets
    jpa:
        database-platform: org.hibernate.dialect.OracleDialect
        hibernate:
            ddl-auto: update
            show_sql: true
            use_sql_comments: true



logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace

oracle:
    net:
    ssl_server_dn_match: true