spring:

    application:
        name: theartimposter
    profiles:
        active: secrets
    jpa:
        database-platform: org.hibernate.dialect.OracleDialect
        hibernate:
            ddl-auto: update
            show_sql: true
            use_sql_comments: true  
mybatis:
  mapper-locations: classpath:config/*.xml



logging:
    level:
        org.apache.coyote.http11.Http11InputBuffer: DEBUG
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace

oracle:
    net:
        ssl_server_dn_match: true
